using MarketSphere.Domain.Enums;

namespace MarketSphere.Application.Modules.Infrastructure.DTOs;

public sealed record ApprovalAssigneeDto(int ApprovalStepAssigneeID, ApprovalAssigneeType AssigneeType, int? RoleID, int? DesignationID, int? UserID, int? EmployeeID, bool IsFallback, int Priority);
public sealed record ApprovalStepDto(int ApprovalStepDefinitionID, int StepNo, string StepName, ApprovalMode ApprovalMode, int MinimumApprovals, bool IsFinalStep, int? EscalationHours, IReadOnlyCollection<ApprovalAssigneeDto> Assignees);
public sealed record ApprovalPolicyDto(int ApprovalPolicyID, ApprovalType ApprovalType, string EntityType, int? BranchID, SalesChannel? Channel, decimal? MinimumAmount, decimal? MaximumAmount, decimal? MinimumDiscountPercent, decimal? MaximumDiscountPercent, DateTime EffectiveFrom, DateTime? EffectiveTo, int Priority, bool IsActive, IReadOnlyCollection<ApprovalStepDto> Steps);
public sealed class SaveApprovalPolicyRequestDto { public ApprovalType ApprovalType { get; init; } public string EntityType { get; init; } = string.Empty; public int? BranchID { get; init; } public SalesChannel? Channel { get; init; } public decimal? MinimumAmount { get; init; } public decimal? MaximumAmount { get; init; } public decimal? MinimumDiscountPercent { get; init; } public decimal? MaximumDiscountPercent { get; init; } public DateTime EffectiveFrom { get; init; } public DateTime? EffectiveTo { get; init; } public int Priority { get; init; } public bool IsActive { get; init; } = true; public IReadOnlyCollection<SaveApprovalStepRequestDto> Steps { get; init; } = Array.Empty<SaveApprovalStepRequestDto>(); }
public sealed class SaveApprovalStepRequestDto { public int StepNo { get; init; } public string StepName { get; init; } = string.Empty; public ApprovalMode ApprovalMode { get; init; } public int MinimumApprovals { get; init; } = 1; public bool IsFinalStep { get; init; } public int? EscalationHours { get; init; } public IReadOnlyCollection<SaveApprovalAssigneeRequestDto> Assignees { get; init; } = Array.Empty<SaveApprovalAssigneeRequestDto>(); }
public sealed class SaveApprovalAssigneeRequestDto { public ApprovalAssigneeType AssigneeType { get; init; } public int? RoleID { get; init; } public int? DesignationID { get; init; } public int? UserID { get; init; } public int? EmployeeID { get; init; } public bool IsFallback { get; init; } public int Priority { get; init; } }
public sealed class CreateApprovalRequestDto { public string ReferenceType { get; init; } = string.Empty; public int ReferenceID { get; init; } public ApprovalType ApprovalType { get; init; } public int? BranchID { get; init; } public SalesChannel? Channel { get; init; } public decimal? Amount { get; init; } public decimal? DiscountPercent { get; init; } }
public sealed class ApprovalActionRequestDto { public ApprovalActionType Action { get; init; } public string? Note { get; init; } public int? DelegateToUserID { get; init; } }
public sealed record ApprovalActionDto(int ApprovalActionID, int StepNo, int ActionByUserID, string ActionByName, ApprovalActionType Action, DateTime ActionAt, string? Note, int? DelegatedFromUserID);
public sealed record ApprovalRequestDto(int ApprovalRequestID, string ReferenceType, int ReferenceID, ApprovalType ApprovalType, int ApprovalPolicyID, int RequestedByUserID, DateTime RequestedAt, int CurrentStepNo, ApprovalRequestStatus Status, DateTime? CompletedAt, IReadOnlyCollection<ApprovalActionDto> Actions);
