using MarketSphere.Domain.Enums;

namespace MarketSphere.Application.Modules.OrderFulfilment.DTOs;

public sealed record ModernTradePurchaseOrderItemDto(int ModernTradePurchaseOrderItemID, string? ExternalItemCode, string? ExternalItemName, int? SKUID, string? SKUCode, ItemMappingStatus MappingStatus, decimal OrderedQuantity, decimal? AgreedUnitPrice, decimal? Discount, string? Note);
public sealed record ModernTradePurchaseOrderListDto(int ModernTradePurchaseOrderID, string PONumber, int ClientID, string ClientName, DateTime PODate, DateTime ReceivedDate, ModernTradePurchaseOrderStatus Status, ModernTradeVerificationStatus VerificationStatus, ModernTradeCompletenessStatus CompletenessStatus);
public sealed record ModernTradePurchaseOrderDetailsDto(int ModernTradePurchaseOrderID, int ClientID, string PONumber, DateTime PODate, DateTime ReceivedDate, int UploadedByEmployeeID, ModernTradePurchaseOrderStatus Status, ModernTradeVerificationStatus VerificationStatus, ModernTradeCompletenessStatus CompletenessStatus, string? VerificationNote, string? RejectionReason, int? VerifiedByEmployeeID, DateTime? VerifiedAt, string? DuplicateHash, DateTime? RequestedDeliveryDate, IReadOnlyCollection<ModernTradePurchaseOrderItemDto> Items);
public sealed class SaveModernTradePurchaseOrderRequestDto { public int ClientID { get; init; } public string PONumber { get; init; } = string.Empty; public DateTime PODate { get; init; } public DateTime ReceivedDate { get; init; } public int UploadedByEmployeeID { get; init; } public string? DuplicateHash { get; init; } public DateTime? RequestedDeliveryDate { get; init; } public IReadOnlyCollection<SaveModernTradePurchaseOrderItemRequestDto> Items { get; init; } = Array.Empty<SaveModernTradePurchaseOrderItemRequestDto>(); }
public sealed class SaveModernTradePurchaseOrderItemRequestDto { public string? ExternalItemCode { get; init; } public string? ExternalItemName { get; init; } public int? SKUID { get; init; } public decimal OrderedQuantity { get; init; } public decimal? AgreedUnitPrice { get; init; } public decimal? Discount { get; init; } public string? Note { get; init; } }
public sealed class MapModernTradePurchaseOrderItemRequestDto { public int SKUID { get; init; } }
public sealed class VerifyModernTradePurchaseOrderRequestDto { public bool Approve { get; init; } public int VerifiedByEmployeeID { get; init; } public string? Note { get; init; } public string? RejectionReason { get; init; } }
