using MarketSphere.Domain.Enums;

namespace MarketSphere.Application.Modules.OrderFulfilment.DTOs;

public sealed record OrderItemDto(int OrderItemID, int SKUID, string SKUCode, string SKUName, decimal OrderedQuantity, decimal FreeQuantity, decimal UnitPrice, decimal DiscountPercent, decimal DiscountAmount, decimal TaxAmount, decimal LineTotal, decimal ApprovedQuantity, decimal DeliveredQuantity, decimal ReturnedQuantity, decimal BackorderQuantity);
public sealed record OrderListDto(int OrderID, string OrderNo, int ClientID, string ClientName, SalesChannel Channel, OrderSource OrderSource, DateTime OrderDate, OrderStatus Status, CreditCheckStatus CreditCheckStatus, decimal NetAmount);
public sealed record OrderDetailsDto(int OrderID, string OrderNo, int ClientID, int? EmployeeID, SalesChannel Channel, OrderSource OrderSource, int? CampaignID, int? QuotationID, int? ModernTradePurchaseOrderID, int? PriceListID, DateTime OrderDate, DateTime? RequestedDeliveryDate, string DeliveryAddressSnapshot, OrderStatus Status, decimal GrossAmount, decimal DiscountAmount, decimal TaxAmount, decimal NetAmount, CreditCheckStatus CreditCheckStatus, int? ApprovalRequestID, IReadOnlyCollection<OrderItemDto> Items);
public sealed class SaveRegularOrderRequestDto { public string OrderNo { get; init; } = string.Empty; public int ClientID { get; init; } public int? EmployeeID { get; init; } public SalesChannel Channel { get; init; } public int? CampaignID { get; init; } public int? PriceListID { get; init; } public DateTime OrderDate { get; init; } public DateTime? RequestedDeliveryDate { get; init; } public string DeliveryAddressSnapshot { get; init; } = string.Empty; public IReadOnlyCollection<SaveOrderItemRequestDto> Items { get; init; } = Array.Empty<SaveOrderItemRequestDto>(); }
public sealed class SaveOrderItemRequestDto { public int SKUID { get; init; } public decimal OrderedQuantity { get; init; } public decimal FreeQuantity { get; init; } public decimal UnitPrice { get; init; } public decimal DiscountPercent { get; init; } public decimal TaxAmount { get; init; } }
public sealed class ConvertQuotationToOrderRequestDto { public string OrderNo { get; init; } = string.Empty; public int QuotationID { get; init; } public int? EmployeeID { get; init; } public DateTime OrderDate { get; init; } public DateTime? RequestedDeliveryDate { get; init; } public string DeliveryAddressSnapshot { get; init; } = string.Empty; }
public sealed class ConvertModernTradePurchaseOrderRequestDto { public string OrderNo { get; init; } = string.Empty; public int ModernTradePurchaseOrderID { get; init; } public int? EmployeeID { get; init; } public int? PriceListID { get; init; } public DateTime OrderDate { get; init; } public string DeliveryAddressSnapshot { get; init; } = string.Empty; }
public sealed class ApproveAndReserveOrderRequestDto { public int WarehouseID { get; init; } public int? ApprovalRequestID { get; init; } public DateTime? ReservationExpiresAt { get; init; } }
public sealed class ChangeOrderStatusRequestDto { public OrderStatus Status { get; init; } }
