using MarketSphere.Domain.Enums;

namespace MarketSphere.Application.Modules.OrderFulfilment.DTOs;

public sealed record ReturnItemDto(int ReturnItemID, int? DeliveryItemID, int SKUID, string SKUCode, int? BatchID, decimal RequestedQuantity, decimal ApprovedQuantity, decimal ReceivedQuantity, ReturnConditionStatus? ConditionStatus, string? InspectionResult, ReturnDisposition Disposition, decimal RestockQuantity, decimal QuarantineQuantity, decimal DamageQuantity, decimal ReplacementQuantity, decimal CreditAmount);
public sealed record ReturnListDto(int ReturnRequestID, string ReturnNo, int ClientID, int OrderID, int? InvoiceID, int? DeliveryID, DateTime RequestDate, string ReturnReason, ReturnRequestStatus Status, ReturnResolutionType? ResolutionType);
public sealed record ReturnDetailsDto(int ReturnRequestID, string ReturnNo, int ClientID, int OrderID, int? InvoiceID, int? DeliveryID, int? ComplaintID, DateTime RequestDate, string ReturnReason, string? Description, ReturnRequestStatus Status, DateTime? ReceivedAtWarehouseAt, ReturnResolutionType? ResolutionType, int? ReplacementOrderID, int? ReplacementDeliveryID, int? SupplierReturnID, int? ResolvedByEmployeeID, DateTime? ResolvedAt, string? ResolutionNote, IReadOnlyCollection<ReturnItemDto> Items);
public sealed class CreateReturnRequestDto { public string ReturnNo { get; init; } = string.Empty; public int ClientID { get; init; } public int OrderID { get; init; } public int? InvoiceID { get; init; } public int? DeliveryID { get; init; } public int? ComplaintID { get; init; } public DateTime RequestDate { get; init; } public string ReturnReason { get; init; } = string.Empty; public string? Description { get; init; } public IReadOnlyCollection<CreateReturnItemRequestDto> Items { get; init; } = Array.Empty<CreateReturnItemRequestDto>(); }
public sealed class CreateReturnItemRequestDto { public int DeliveryItemID { get; init; } public decimal RequestedQuantity { get; init; } }
public sealed class ApproveReturnRequestDto { public IReadOnlyCollection<ApproveReturnItemRequestDto> Items { get; init; } = Array.Empty<ApproveReturnItemRequestDto>(); }
public sealed class ApproveReturnItemRequestDto { public int ReturnItemID { get; init; } public decimal ApprovedQuantity { get; init; } }
public sealed class ResolveReturnRequestDto { public int WarehouseID { get; init; } public int ResolvedByEmployeeID { get; init; } public ReturnResolutionType ResolutionType { get; init; } public string ResolutionNote { get; init; } = string.Empty; public string? CreditNoteNo { get; init; } public IReadOnlyCollection<ResolveReturnItemRequestDto> Items { get; init; } = Array.Empty<ResolveReturnItemRequestDto>(); }
public sealed class ResolveReturnItemRequestDto { public int ReturnItemID { get; init; } public decimal ReceivedQuantity { get; init; } public ReturnConditionStatus ConditionStatus { get; init; } public string? InspectionResult { get; init; } public ReturnDisposition Disposition { get; init; } public decimal RestockQuantity { get; init; } public decimal QuarantineQuantity { get; init; } public decimal DamageQuantity { get; init; } public decimal ReplacementQuantity { get; init; } public decimal CreditAmount { get; init; } }
