using MarketSphere.Application.Common.Interfaces;
using MarketSphere.Application.Common.Mapping;
using MarketSphere.Application.Common.Models;
using MarketSphere.Application.Common.Validation;
using MarketSphere.Application.Modules.CRM.DTOs;
using MarketSphere.Application.Modules.CRM.Interfaces;
using MarketSphere.Domain.Entities.CRM;
using MarketSphere.Domain.Enums;
using MarketSphere.Domain.Exceptions;
using Microsoft.EntityFrameworkCore;

namespace MarketSphere.Application.Modules.CRM.Services;

public sealed class ComplaintService : IComplaintService
{
    private readonly IApplicationDbContext _db; private readonly IDateTimeProvider _clock;
    public ComplaintService(IApplicationDbContext db, IDateTimeProvider clock) { _db = db; _clock = clock; }
    public Task<PagedResult<ComplaintListDto>> GetPagedAsync(PagedRequest r, bool slaBreachedOnly, CancellationToken ct = default)
    {
        var q = _db.Complaints.AsNoTracking(); if (slaBreachedOnly) q = q.Where(x => x.SLADueAt < _clock.UtcNow && x.Status != ComplaintStatus.Resolved && x.Status != ComplaintStatus.Closed && x.Status != ComplaintStatus.Rejected); if (!string.IsNullOrWhiteSpace(r.Search)) { var s = r.Search.Trim(); q = q.Where(x => x.ComplaintNo.Contains(s) || x.Subject.Contains(s) || x.Client.ClientName.Contains(s)); }
        return CrmServiceHelper.ToPagedAsync(q.OrderByDescending(x => x.OpenedAt).Select(x => new ComplaintListDto(x.ComplaintID, x.ComplaintNo, x.ClientID, x.ComplaintCategory, x.Priority, x.Subject, x.Status, x.OpenedAt, x.SLADueAt, x.AssignedEmployeeID)), r, ct);
    }
    public async Task<ComplaintDetailsDto> GetByIdAsync(int id, CancellationToken ct = default) => await _db.Complaints.AsNoTracking().Where(x => x.ComplaintID == id).Select(x => new ComplaintDetailsDto(x.ComplaintID, x.ComplaintNo, x.ClientID, x.OrderID, x.InvoiceID, x.DeliveryID, x.ComplaintCategory, x.Priority, x.Subject, x.Details, x.AssignedEmployeeID, x.Status, x.OpenedAt, x.SLADueAt, x.ResolvedAt, x.ResolutionNote, x.SatisfactionScore)).SingleOrDefaultAsync(ct) ?? throw new NotFoundException("Complaint was not found.");
    public async Task<int> CreateAsync(SaveComplaintRequestDto r, CancellationToken ct = default) { Validate(r); await ValidateRefs(r, ct); var no = r.ComplaintNo.NormalizeCode(); if (await _db.Complaints.AnyAsync(x => x.ComplaintNo == no, ct)) throw new ConflictException(BusinessRuleMessages.DuplicateCode); var e = new Complaint { ComplaintNo = no, OpenedAt = _clock.UtcNow, Status = ComplaintStatus.Open }; Apply(e, r); await _db.AddAsync(e, ct); await _db.SaveChangesAsync(ct); return e.ComplaintID; }
    public async Task UpdateAsync(int id, SaveComplaintRequestDto r, CancellationToken ct = default) { Validate(r); await ValidateRefs(r, ct); var e = await CrmServiceHelper.RequireAsync(_db.Complaints.Where(x => x.ComplaintID == id), "Complaint", ct); if (e.Status is ComplaintStatus.Resolved or ComplaintStatus.Closed) throw new BusinessRuleException("A resolved or closed complaint cannot be edited."); var no = r.ComplaintNo.NormalizeCode(); if (await _db.Complaints.AnyAsync(x => x.ComplaintNo == no && x.ComplaintID != id, ct)) throw new ConflictException(BusinessRuleMessages.DuplicateCode); e.ComplaintNo = no; Apply(e, r); await _db.SaveChangesAsync(ct); }
    public async Task ChangeStatusAsync(int id, ChangeComplaintStatusRequestDto r, CancellationToken ct = default) { var e = await CrmServiceHelper.RequireAsync(_db.Complaints.Where(x => x.ComplaintID == id), "Complaint", ct); if (e.Status == r.Status) return; var allowed = e.Status switch { ComplaintStatus.Open => r.Status is ComplaintStatus.Assigned or ComplaintStatus.InProgress or ComplaintStatus.Rejected, ComplaintStatus.Assigned => r.Status is ComplaintStatus.InProgress or ComplaintStatus.WaitingForCustomer or ComplaintStatus.Resolved, ComplaintStatus.InProgress => r.Status is ComplaintStatus.WaitingForCustomer or ComplaintStatus.Resolved, ComplaintStatus.WaitingForCustomer => r.Status is ComplaintStatus.InProgress or ComplaintStatus.Resolved, ComplaintStatus.Resolved => r.Status == ComplaintStatus.Closed, _ => false }; if (!allowed) throw new BusinessRuleException(BusinessRuleMessages.InvalidStatusTransition); if (r.Status is ComplaintStatus.Resolved or ComplaintStatus.Closed) ValidationHelper.RequireNotBlank(r.ResolutionNote, nameof(r.ResolutionNote), 1000); if (r.SatisfactionScore.HasValue) ValidationHelper.Require(r.SatisfactionScore is >= 1 and <= 5, nameof(r.SatisfactionScore), "Satisfaction score must be between 1 and 5."); e.Status = r.Status; e.ResolutionNote = r.ResolutionNote.NullIfWhiteSpace(); e.SatisfactionScore = r.SatisfactionScore; e.ResolvedAt = r.Status is ComplaintStatus.Resolved or ComplaintStatus.Closed ? _clock.UtcNow : null; await _db.SaveChangesAsync(ct); }
    private async Task ValidateRefs(SaveComplaintRequestDto r, CancellationToken ct) { if (!await _db.Clients.AnyAsync(x => x.ClientID == r.ClientID, ct)) throw new NotFoundException("Client was not found."); if (r.AssignedEmployeeID.HasValue && !await _db.Employees.AnyAsync(x => x.EmployeeID == r.AssignedEmployeeID, ct)) throw new NotFoundException("Assigned employee was not found."); if (r.OrderID.HasValue && !await _db.Orders.AnyAsync(x => x.OrderID == r.OrderID && x.ClientID == r.ClientID, ct)) throw new BusinessRuleException("The order does not belong to the selected client."); if (r.InvoiceID.HasValue && !await _db.Invoices.AnyAsync(x => x.InvoiceID == r.InvoiceID && x.ClientID == r.ClientID, ct)) throw new BusinessRuleException("The invoice does not belong to the selected client."); if (r.DeliveryID.HasValue && !await _db.Deliveries.AnyAsync(x => x.DeliveryID == r.DeliveryID && x.Order.ClientID == r.ClientID, ct)) throw new BusinessRuleException("The delivery does not belong to the selected client."); }
    private static void Validate(SaveComplaintRequestDto r) { ValidationHelper.RequireNotBlank(r.ComplaintNo, nameof(r.ComplaintNo), 40); CrmServiceHelper.ValidatePositiveId(r.ClientID, nameof(r.ClientID)); ValidationHelper.RequireNotBlank(r.Subject, nameof(r.Subject), 200); ValidationHelper.RequireNotBlank(r.Details, nameof(r.Details), 2000); }
    private static void Apply(Complaint e, SaveComplaintRequestDto r) { e.ClientID = r.ClientID; e.OrderID = r.OrderID; e.InvoiceID = r.InvoiceID; e.DeliveryID = r.DeliveryID; e.ComplaintCategory = r.ComplaintCategory; e.Priority = r.Priority; e.Subject = r.Subject.Trim(); e.Details = r.Details.Trim(); e.AssignedEmployeeID = r.AssignedEmployeeID; e.SLADueAt = r.SLADueAt; }
}
