using MarketSphere.Application.Common.Interfaces;
using MarketSphere.Application.Common.Mapping;
using MarketSphere.Application.Common.Models;
using MarketSphere.Application.Common.Validation;
using MarketSphere.Application.Modules.CRM.DTOs;
using MarketSphere.Application.Modules.CRM.Interfaces;
using MarketSphere.Domain.Entities.CRM;
using MarketSphere.Domain.Enums;
using MarketSphere.Domain.Exceptions;
using Microsoft.EntityFrameworkCore;

namespace MarketSphere.Application.Modules.CRM.Services;

public sealed class ReactivationService : IReactivationService
{
    private readonly IApplicationDbContext _db; private readonly IDateTimeProvider _clock;
    public ReactivationService(IApplicationDbContext db, IDateTimeProvider clock) { _db = db; _clock = clock; }
    public Task<PagedResult<ReactivationCaseDto>> GetPagedAsync(PagedRequest r, CancellationToken ct = default) { var q = _db.ReactivationCases.AsNoTracking(); if (!string.IsNullOrWhiteSpace(r.Search)) { var s = r.Search.Trim(); q = q.Where(x => x.Client.ClientCode.Contains(s) || x.Client.ClientName.Contains(s)); } return CrmServiceHelper.ToPagedAsync(Project(q.OrderBy(x => x.Status).ThenByDescending(x => x.OpenedAt)), r, ct); }
    public async Task<ReactivationCaseDto> GetByIdAsync(int id, CancellationToken ct = default) => await Project(_db.ReactivationCases.AsNoTracking().Where(x => x.ReactivationCaseID == id)).SingleOrDefaultAsync(ct) ?? throw new NotFoundException("Reactivation case was not found.");
    public async Task<int> CreateAsync(CreateReactivationCaseRequestDto r, CancellationToken ct = default) { CrmServiceHelper.ValidatePositiveId(r.ClientID, nameof(r.ClientID)); CrmServiceHelper.ValidatePositiveId(r.AssignedEmployeeID, nameof(r.AssignedEmployeeID)); var client = await CrmServiceHelper.RequireAsync(_db.Clients.Where(x => x.ClientID == r.ClientID), "Client", ct); if (client.LifecycleStatus == ClientLifecycleStatus.Active) throw new BusinessRuleException("An active client does not require reactivation."); if (!await _db.Employees.AnyAsync(x => x.EmployeeID == r.AssignedEmployeeID, ct)) throw new NotFoundException("Assigned employee was not found."); if (r.CampaignID.HasValue && !await _db.Campaigns.AnyAsync(x => x.CampaignID == r.CampaignID, ct)) throw new NotFoundException("Campaign was not found."); if (await _db.ReactivationCases.AnyAsync(x => x.ClientID == r.ClientID && x.Status != ReactivationCaseStatus.Successful && x.Status != ReactivationCaseStatus.Unsuccessful && x.Status != ReactivationCaseStatus.Closed, ct)) throw new ConflictException("An active reactivation case already exists for the client."); var e = new ReactivationCase { ClientID = r.ClientID, InactiveAt = r.InactiveAt, ChurnReason = r.ChurnReason.NullIfWhiteSpace(), CampaignID = r.CampaignID, AssignedEmployeeID = r.AssignedEmployeeID, OpenedAt = _clock.UtcNow, Status = ReactivationCaseStatus.Open }; await _db.AddAsync(e, ct); client.LifecycleStatus = ClientLifecycleStatus.ReactivationInProgress; client.IsActive = true; await _db.SaveChangesAsync(ct); return e.ReactivationCaseID; }
    public async Task ResolveAsync(int id, ResolveReactivationCaseRequestDto r, CancellationToken ct = default) { await _db.ExecuteInTransactionAsync(async token => { var e = await CrmServiceHelper.RequireAsync(_db.ReactivationCases.Where(x => x.ReactivationCaseID == id), "Reactivation case", token); if (e.Status is ReactivationCaseStatus.Successful or ReactivationCaseStatus.Unsuccessful or ReactivationCaseStatus.Closed) throw new BusinessRuleException("The reactivation case is already closed."); if (r.Status == ReactivationCaseStatus.Successful) { ValidationHelper.Require(r.ReactivationResult.HasValue, nameof(r.ReactivationResult), "Reactivation result is required."); ValidationHelper.Require(r.ReactivationResult is ReactivationResult.Reordered or ReactivationResult.Interested, nameof(r.ReactivationResult), "A successful case requires a positive result."); if (r.ReactivationResult == ReactivationResult.Reordered) { ValidationHelper.Require(r.RepeatOrderID.HasValue, nameof(r.RepeatOrderID), "Repeat order is required for a reordered result."); if (!await _db.Orders.AnyAsync(x => x.OrderID == r.RepeatOrderID && x.ClientID == e.ClientID, token)) throw new BusinessRuleException("The repeat order does not belong to the reactivated client."); } } if (r.Status == ReactivationCaseStatus.Unsuccessful) ValidationHelper.Require(r.ReactivationResult.HasValue, nameof(r.ReactivationResult), "Reactivation result is required."); e.Status = r.Status; e.ReactivationResult = r.ReactivationResult; e.RepeatOrderID = r.RepeatOrderID; e.ReactivatedAt = r.Status == ReactivationCaseStatus.Successful ? _clock.UtcNow : null; var client = await CrmServiceHelper.RequireAsync(_db.Clients.Where(x => x.ClientID == e.ClientID), "Client", token); if (r.Status == ReactivationCaseStatus.Successful) { client.LifecycleStatus = ClientLifecycleStatus.Active; client.IsActive = true; } else if (r.Status == ReactivationCaseStatus.Unsuccessful) { client.LifecycleStatus = ClientLifecycleStatus.Churned; client.IsActive = false; } await _db.SaveChangesAsync(token); return true; }, ct); }
    private static IQueryable<ReactivationCaseDto> Project(IQueryable<ReactivationCase> q) => q.Select(x => new ReactivationCaseDto(x.ReactivationCaseID, x.ClientID, x.InactiveAt, x.ChurnReason, x.CampaignID, x.AssignedEmployeeID, x.OpenedAt, x.Status, x.ReactivationResult, x.ReactivatedAt, x.RepeatOrderID));
}
