using MarketSphere.Application.Common.Interfaces;
using MarketSphere.Application.Common.Models;
using MarketSphere.Application.Common.Validation;
using MarketSphere.Application.Modules.OrderFulfilment.DTOs;
using MarketSphere.Application.Modules.OrderFulfilment.Interfaces;
using MarketSphere.Domain.Entities.OrderFulfilment;
using MarketSphere.Domain.Enums;
using MarketSphere.Domain.Exceptions;
using Microsoft.EntityFrameworkCore;

namespace MarketSphere.Application.Modules.OrderFulfilment.Services;

public sealed class PickListService : IPickListService
{
    private readonly IApplicationDbContext _db; private readonly IDateTimeProvider _clock;
    public PickListService(IApplicationDbContext db, IDateTimeProvider clock) { _db = db; _clock = clock; }
    public Task<PagedResult<PickListListDto>> GetAsync(PagedRequest r, CancellationToken ct = default) { var q = _db.PickLists.AsNoTracking(); if (!string.IsNullOrWhiteSpace(r.Search)) { var s = r.Search.Trim(); q = q.Where(x => x.PickListNo.Contains(s) || x.Order.OrderNo.Contains(s)); } return OrderFulfilmentServiceHelper.ToPagedAsync(q.OrderByDescending(x => x.PickListID).Select(x => new PickListListDto(x.PickListID, x.PickListNo, x.OrderID, x.InvoiceID, x.WarehouseID, x.WaveNo, x.Status, x.ReleasedAt, x.VerifiedAt)), r, ct); }
    public async Task<PickListDetailsDto> GetByIdAsync(int id, CancellationToken ct = default) { var e = await OrderFulfilmentServiceHelper.RequireAsync(_db.PickLists.AsNoTracking().Where(x => x.PickListID == id), "Pick list", ct); var items = await _db.PickListItems.AsNoTracking().Where(x => x.PickListID == id).Select(x => new PickListItemDto(x.PickListItemID, x.OrderItemID, x.StockReservationID, x.SKUID, x.SKU.SKUCode, x.BatchID, x.RequestedQuantity, x.PickedQuantity, x.ShortQuantity, x.PickedByEmployeeID, x.PickedAt, x.VerificationNote)).ToListAsync(ct); return new(e.PickListID, e.PickListNo, e.OrderID, e.InvoiceID, e.WarehouseID, e.WaveNo, e.Status, e.ReleasedAt, e.ReleasedByEmployeeID, e.VerifiedByEmployeeID, e.VerifiedAt, e.Note, items); }
    public async Task<int> CreateAsync(CreatePickListRequestDto r, CancellationToken ct = default) => await _db.ExecuteInTransactionAsync(async token => { if (string.IsNullOrWhiteSpace(r.PickListNo)) throw new BusinessRuleException("Pick-list number is required."); var no = r.PickListNo.Trim().ToUpperInvariant(); if (await _db.PickLists.AnyAsync(x => x.PickListNo == no, token)) throw new ConflictException("Pick-list number already exists."); var order = await OrderFulfilmentServiceHelper.RequireAsync(_db.Orders.Where(x => x.OrderID == r.OrderID), "Order", token); if (order.Status is not (OrderStatus.StockAllocated or OrderStatus.Invoiced)) throw new BusinessRuleException("A stock-allocated or invoiced order is required."); if (r.InvoiceID.HasValue && !await _db.Invoices.AnyAsync(x => x.InvoiceID == r.InvoiceID && x.OrderID == r.OrderID, token)) throw new BusinessRuleException("The invoice does not belong to the selected order."); var reservations = await _db.StockReservations.Where(x => x.OrderItem.OrderID == r.OrderID && x.WarehouseID == r.WarehouseID && x.ReservationStatus == StockReservationStatus.Active).ToListAsync(token); if (reservations.Count == 0) throw new BusinessRuleException("No active reservations were found for the selected warehouse."); var pick = new PickList { PickListNo = no, OrderID = r.OrderID, InvoiceID = r.InvoiceID, WarehouseID = r.WarehouseID, WaveNo = string.IsNullOrWhiteSpace(r.WaveNo) ? null : r.WaveNo.Trim(), Note = string.IsNullOrWhiteSpace(r.Note) ? null : r.Note.Trim(), Status = PickListStatus.Draft }; await _db.AddAsync(pick, token); foreach (var reservation in reservations) await _db.AddAsync(new PickListItem { PickList = pick, OrderItemID = reservation.OrderItemID, StockReservationID = reservation.StockReservationID, SKUID = reservation.SKUID, BatchID = reservation.BatchID, RequestedQuantity = reservation.ReservedQuantity }, token); await _db.SaveChangesAsync(token); return pick.PickListID; }, ct);
    public async Task ReleaseAsync(int id, ReleasePickListRequestDto r, CancellationToken ct = default) { var e = await OrderFulfilmentServiceHelper.RequireAsync(_db.PickLists.Where(x => x.PickListID == id), "Pick list", ct); if (e.Status != PickListStatus.Draft) throw new BusinessRuleException("Only a draft pick list can be released."); if (!await _db.Employees.AnyAsync(x => x.EmployeeID == r.ReleasedByEmployeeID, ct)) throw new NotFoundException("Releasing employee was not found."); e.Status = PickListStatus.Released; e.ReleasedAt = _clock.UtcNow; e.ReleasedByEmployeeID = r.ReleasedByEmployeeID; await _db.SaveChangesAsync(ct); }
    public async Task RecordPickAsync(int id, RecordPickRequestDto r, CancellationToken ct = default) { var e = await OrderFulfilmentServiceHelper.RequireAsync(_db.PickLists.Where(x => x.PickListID == id), "Pick list", ct); if (e.Status is not (PickListStatus.Released or PickListStatus.Picking or PickListStatus.PartiallyPicked)) throw new BusinessRuleException("The pick list is not open for picking."); var item = await OrderFulfilmentServiceHelper.RequireAsync(_db.PickListItems.Where(x => x.PickListID == id && x.PickListItemID == r.PickListItemID), "Pick-list item", ct); if (r.PickedQuantity < 0 || r.ShortQuantity < 0 || r.PickedQuantity + r.ShortQuantity > item.RequestedQuantity) throw new BusinessRuleException(BusinessRuleMessages.PickQuantityInvalid); item.PickedQuantity = r.PickedQuantity; item.ShortQuantity = r.ShortQuantity; item.PickedByEmployeeID = r.PickedByEmployeeID; item.PickedAt = _clock.UtcNow; item.VerificationNote = string.IsNullOrWhiteSpace(r.VerificationNote) ? null : r.VerificationNote.Trim(); var all = await _db.PickListItems.Where(x => x.PickListID == id).ToListAsync(ct); e.Status = all.All(x => x.PickedQuantity + x.ShortQuantity == x.RequestedQuantity) ? all.Any(x => x.ShortQuantity > 0) ? PickListStatus.PartiallyPicked : PickListStatus.Picked : PickListStatus.Picking; await _db.SaveChangesAsync(ct); }
    public async Task VerifyAsync(int id, VerifyPickListRequestDto r, CancellationToken ct = default) { var e = await OrderFulfilmentServiceHelper.RequireAsync(_db.PickLists.Where(x => x.PickListID == id), "Pick list", ct); var items = await _db.PickListItems.Where(x => x.PickListID == id).ToListAsync(ct); if (e.Status is not (PickListStatus.Picked or PickListStatus.PartiallyPicked) || items.Any(x => x.PickedQuantity + x.ShortQuantity != x.RequestedQuantity)) throw new BusinessRuleException("All pick-list items must be completely picked or marked short before verification."); e.Status = PickListStatus.Verified; e.VerifiedByEmployeeID = r.VerifiedByEmployeeID; e.VerifiedAt = _clock.UtcNow; e.Note = string.IsNullOrWhiteSpace(r.Note) ? e.Note : r.Note.Trim(); var order = await _db.Orders.SingleAsync(x => x.OrderID == e.OrderID, ct); order.Status = OrderStatus.ReadyForDispatch; await _db.SaveChangesAsync(ct); }
}
