import { environment } from '../../../environments/environment';

const api = environment.apiBaseUrl.replace(/\/$/, '');

export const API_ENDPOINTS = {
  auth: {
    login: `${api}/auth/login`,
    refresh: `${api}/auth/refresh`,
    changePassword: `${api}/auth/change-password`,
    activateAccount: `${api}/auth/activate-account`,
    resetPassword: `${api}/auth/reset-password`,
    currentUser: `${api}/auth/me`,
    revokeSession: (userSessionID: number) => `${api}/auth/sessions/${userSessionID}/revoke`,
  },
  users: {
    root: `${api}/users`,
    byID: (userID: number) => `${api}/users/${userID}`,
    status: (userID: number) => `${api}/users/${userID}/status`,
    roles: (userID: number) => `${api}/users/${userID}/roles`,
  },
  roles: {
    root: `${api}/roles`,
    byID: (roleID: number) => `${api}/roles/${roleID}`,
    permissions: (roleID: number) => `${api}/roles/${roleID}/permissions`,
  },
  employees: {
    root: `${api}/employees`,
    byID: (employeeID: number) => `${api}/employees/${employeeID}`,
  },
  organization: {
    companies: `${api}/organization/companies`,
    company: (companyID: number) => `${api}/organization/companies/${companyID}`,
    branches: `${api}/organization/branches`,
    branch: (branchID: number) => `${api}/organization/branches/${branchID}`,
  },
  geography: {
    regions: `${api}/geography/regions`,
    region: (regionID: number) => `${api}/geography/regions/${regionID}`,
    areas: `${api}/geography/areas`,
    area: (areaID: number) => `${api}/geography/areas/${areaID}`,
    territories: `${api}/geography/territories`,
    territory: (territoryID: number) => `${api}/geography/territories/${territoryID}`,
  },
  routes: {
    root: `${api}/routes`,
    byID: (routeID: number) => `${api}/routes/${routeID}`,
    outlets: (routeID: number) => `${api}/routes/${routeID}/outlets`,
    addOutlet: `${api}/routes/outlets`,
    employeeRouteAssignments: `${api}/routes/employee-route-assignments`,
    employeeTerritoryAssignments: `${api}/routes/employee-territory-assignments`,
  },
  settings: {
    root: `${api}/settings`,
    byID: (settingID: number) => `${api}/settings/${settingID}`,
  },
  audit: {
    logs: `${api}/audit/logs`,
    statusHistory: `${api}/audit/status-history`,
  },
  products: {
    root: `${api}/products`,
    categories: `${api}/products/categories`,
    category: (productCategoryID: number) => `${api}/products/categories/${productCategoryID}`,
    categoryStatus: (productCategoryID: number) =>
      `${api}/products/categories/${productCategoryID}/status`,
    brands: `${api}/products/brands`,
    brand: (brandID: number) => `${api}/products/brands/${brandID}`,
    brandStatus: (brandID: number) => `${api}/products/brands/${brandID}/status`,
    list: `${api}/products/products`,
    byID: (productID: number) => `${api}/products/${productID}`,
    status: (productID: number) => `${api}/products/${productID}/status`,
    skus: `${api}/products/skus`,
    sku: (skuID: number) => `${api}/products/skus/${skuID}`,
    skuStatus: (skuID: number) => `${api}/products/skus/${skuID}/status`,
  },
  pricing: {
    priceLists: `${api}/pricing/price-lists`,
    priceList: (priceListID: number) => `${api}/pricing/price-lists/${priceListID}`,
    priceListStatus: (priceListID: number) => `${api}/pricing/price-lists/${priceListID}/status`,
    discountRules: `${api}/pricing/discount-rules`,
    discountRule: (standardDiscountRuleID: number) =>
      `${api}/pricing/discount-rules/${standardDiscountRuleID}`,
    discountRuleStatus: (standardDiscountRuleID: number) =>
      `${api}/pricing/discount-rules/${standardDiscountRuleID}/status`,
    resolve: `${api}/pricing/resolve`,
  },
  clients: {
    root: `${api}/clients`,
    dashboard: `${api}/clients/dashboard`,
    byID: (clientID: number) => `${api}/clients/${clientID}`,
    contacts: (clientID: number) => `${api}/clients/${clientID}/contacts`,
    contact: (clientContactID: number) => `${api}/clients/contacts/${clientContactID}`,
    creditProfile: (clientID: number) => `${api}/clients/${clientID}/credit-profile`,
    lifecycle: (clientID: number) => `${api}/clients/${clientID}/lifecycle`,
    segments: `${api}/clients/segments`,
    assignSegment: (clientID: number) => `${api}/clients/${clientID}/segments`,
    endSegmentAssignment: (clientSegmentAssignmentID: number) =>
      `${api}/clients/segment-assignments/${clientSegmentAssignmentID}/end`,
  },
  leads: {
    root: `${api}/leads`,
    byID: (leadID: number) => `${api}/leads/${leadID}`,
    status: (leadID: number) => `${api}/leads/${leadID}/status`,
    recalculateScore: (leadID: number) => `${api}/leads/${leadID}/score/recalculate`,
    duplicates: (leadID: number) => `${api}/leads/${leadID}/duplicates`,
    duplicateReviews: `${api}/leads/duplicate-reviews`,
    resolveDuplicateReview: (duplicateReviewCaseID: number) =>
      `${api}/leads/duplicate-reviews/${duplicateReviewCaseID}/resolve`,
    scoreRules: `${api}/leads/score-rules`,
    convertToClient: (leadID: number) => `${api}/leads/${leadID}/convert-to-client`,
  },
  crmActivities: {
    root: `${api}/crm-activities`,
    byID: (activityID: number) => `${api}/crm-activities/${activityID}`,
  },
  crmTasks: {
    root: `${api}/crm-tasks`,
    byID: (taskID: number) => `${api}/crm-tasks/${taskID}`,
    status: (taskID: number) => `${api}/crm-tasks/${taskID}/status`,
  },
  opportunities: {
    root: `${api}/opportunities`,
    byID: (opportunityID: number) => `${api}/opportunities/${opportunityID}`,
    stage: (opportunityID: number) => `${api}/opportunities/${opportunityID}/stage`,
  },
  quotations: {
    root: `${api}/quotations`,
    byID: (quotationID: number) => `${api}/quotations/${quotationID}`,
    versions: (quotationID: number) => `${api}/quotations/${quotationID}/versions`,
    status: (quotationID: number) => `${api}/quotations/${quotationID}/status`,
  },
  complaints: {
    root: `${api}/complaints`,
    byID: (complaintID: number) => `${api}/complaints/${complaintID}`,
    status: (complaintID: number) => `${api}/complaints/${complaintID}/status`,
  },
  reactivation: {
    root: `${api}/reactivation`,
    byID: (reactivationCaseID: number) => `${api}/reactivation/${reactivationCaseID}`,
    resolve: (reactivationCaseID: number) => `${api}/reactivation/${reactivationCaseID}/resolve`,
  },
  campaigns: {
    root: `${api}/campaigns`,
    byID: (campaignID: number) => `${api}/campaigns/${campaignID}`,
    status: (campaignID: number) => `${api}/campaigns/${campaignID}/status`,
    targets: (campaignID: number) => `${api}/campaigns/${campaignID}/targets`,
    target: (campaignTargetID: number) => `${api}/campaigns/targets/${campaignTargetID}`,
    offers: (campaignID: number) => `${api}/campaigns/${campaignID}/offers`,
    offer: (campaignOfferID: number) => `${api}/campaigns/offers/${campaignOfferID}`,
    expenses: (campaignID: number) => `${api}/campaigns/${campaignID}/expenses`,
    expense: (campaignExpenseID: number) => `${api}/campaigns/expenses/${campaignExpenseID}`,
    expenseStatus: (campaignExpenseID: number) =>
      `${api}/campaigns/expenses/${campaignExpenseID}/status`,
    attributions: (campaignID: number) => `${api}/campaigns/${campaignID}/attributions`,
    roi: (campaignID: number) => `${api}/campaigns/${campaignID}/roi`,
  },
  visits: {
    root: `${api}/visits`,
    byID: (visitID: number) => `${api}/visits/${visitID}`,
    checkIn: `${api}/visits/check-in`,
    checkOut: (visitID: number) => `${api}/visits/${visitID}/check-out`,
    cancel: (visitID: number) => `${api}/visits/${visitID}/cancel`,
  },
  sampling: {
    root: `${api}/sampling`,
    byID: (samplingLogID: number) => `${api}/sampling/${samplingLogID}`,
  },
  feedback: {
    root: `${api}/feedback`,
    byID: (feedbackID: number) => `${api}/feedback/${feedbackID}`,
  },
  marketObservations: {
    root: `${api}/market-observations`,
    byID: (marketObservationID: number) => `${api}/market-observations/${marketObservationID}`,
  },
  bpSellOut: {
    root: `${api}/bp-sell-out`,
    byID: (bpSellOutID: number) => `${api}/bp-sell-out/${bpSellOutID}`,
    verify: (bpSellOutID: number) => `${api}/bp-sell-out/${bpSellOutID}/verify`,
  },
  fieldWorkspace: {
    summary: `${api}/field-workspace/summary`,
    assignedClients: `${api}/field-workspace/assigned-clients`,
    myVisits: `${api}/field-workspace/my-visits`,
    activeVisit: `${api}/field-workspace/active-visit`,
  },
  notifications: {
    root: `${api}/notifications`,
    markRead: (notificationID: number) => `${api}/notifications/${notificationID}/read`,
    markAllRead: `${api}/notifications/read-all`,
  },
  systemChecks: {
    run: `${api}/system-checks/run`,
  },
  files: {
    root: `${api}/files`,
    byID: (fileAttachmentID: number) => `${api}/files/${fileAttachmentID}`,
    download: (fileAttachmentID: number) => `${api}/files/${fileAttachmentID}/download`,
  },
  suppliers: {
    root: `${api}/suppliers`,
    byID: (supplierID: number) => `${api}/suppliers/${supplierID}`,
    status: (supplierID: number) => `${api}/suppliers/${supplierID}/status`,
    products: (supplierID: number) => `${api}/suppliers/${supplierID}/products`,
  },
  purchaseRequisitions: {
    root: `${api}/purchase-requisitions`,
    byID: (id: number) => `${api}/purchase-requisitions/${id}`,
    status: (id: number) => `${api}/purchase-requisitions/${id}/status`,
  },
  purchaseOrders: {
    root: `${api}/purchase-orders`,
    byID: (id: number) => `${api}/purchase-orders/${id}`,
    status: (id: number) => `${api}/purchase-orders/${id}/status`,
  },
  goodsReceipts: {
    root: `${api}/goods-receipts`,
    byID: (id: number) => `${api}/goods-receipts/${id}`,
    qualityCheck: (id: number) => `${api}/goods-receipts/${id}/quality-check`,
    post: (id: number) => `${api}/goods-receipts/${id}/post`,
  },
  purchaseInvoices: {
    root: `${api}/purchase-invoices`,
    byID: (id: number) => `${api}/purchase-invoices/${id}`,
    confirm: (id: number) => `${api}/purchase-invoices/${id}/confirm`,
    payments: `${api}/purchase-invoices/payments`,
    paymentStatus: (supplierPaymentID: number) =>
      `${api}/purchase-invoices/payments/${supplierPaymentID}/status`,
    invoicePayments: (purchaseInvoiceID: number) =>
      `${api}/purchase-invoices/${purchaseInvoiceID}/payments`,
  },
  supplierReturns: {
    root: `${api}/supplier-returns`,
    byID: (id: number) => `${api}/supplier-returns/${id}`,
    status: (id: number) => `${api}/supplier-returns/${id}/status`,
    post: (id: number) => `${api}/supplier-returns/${id}/post`,
  },
  warehouses: {
    root: `${api}/warehouses`,
    byID: (id: number) => `${api}/warehouses/${id}`,
    status: (id: number) => `${api}/warehouses/${id}/status`,
  },
  stock: {
    balances: `${api}/stock/balances`,
    batches: `${api}/stock/batches`,
    movements: `${api}/stock/movements`,
    reservations: `${api}/stock/reservations`,
  },
  stockTransfers: {
    root: `${api}/stock-transfers`,
    byID: (id: number) => `${api}/stock-transfers/${id}`,
    submit: (id: number) => `${api}/stock-transfers/${id}/submit`,
    approve: (id: number) => `${api}/stock-transfers/${id}/approve`,
    dispatch: (id: number) => `${api}/stock-transfers/${id}/dispatch`,
    receive: (id: number) => `${api}/stock-transfers/${id}/receive`,
  },
  stockAdjustments: {
    root: `${api}/stock-adjustments`,
    byID: (id: number) => `${api}/stock-adjustments/${id}`,
    status: (id: number) => `${api}/stock-adjustments/${id}/status`,
    post: (id: number) => `${api}/stock-adjustments/${id}/post`,
  },
  modernTradePurchaseOrders: {
    root: `${api}/mt-purchase-orders`,
    byID: (id: number) => `${api}/mt-purchase-orders/${id}`,
    itemMapping: (itemID: number) => `${api}/mt-purchase-orders/items/${itemID}/mapping`,
    submit: (id: number) => `${api}/mt-purchase-orders/${id}/submit`,
    verify: (id: number) => `${api}/mt-purchase-orders/${id}/verify`,
  },
  orders: {
    root: `${api}/orders`,
    byID: (id: number) => `${api}/orders/${id}`,
    regular: `${api}/orders/regular`,
    fromQuotation: `${api}/orders/from-quotation`,
    fromModernTradePurchaseOrder: `${api}/orders/from-mt-purchase-order`,
    submit: (id: number) => `${api}/orders/${id}/submit`,
    approveAndReserve: (id: number) => `${api}/orders/${id}/approve-and-reserve`,
    status: (id: number) => `${api}/orders/${id}/status`,
    appliedOffers: (id: number) => `${api}/orders/${id}/applied-offers`,
    applyOffer: `${api}/orders/applied-offers`,
    removeOffer: (id: number) => `${api}/orders/applied-offers/${id}`,
  },
  approvals: {
    root: `${api}/approvals`,
    byID: (id: number) => `${api}/approvals/${id}`,
    actions: (id: number) => `${api}/approvals/${id}/actions`,
    cancel: (id: number) => `${api}/approvals/${id}/cancel`,
  },
  invoices: {
    root: `${api}/invoices`,
    byID: (id: number) => `${api}/invoices/${id}`,
    status: (id: number) => `${api}/invoices/${id}/status`,
  },
  pickLists: {
    root: `${api}/pick-lists`,
    byID: (id: number) => `${api}/pick-lists/${id}`,
    release: (id: number) => `${api}/pick-lists/${id}/release`,
    recordPick: (id: number) => `${api}/pick-lists/${id}/record-pick`,
    verify: (id: number) => `${api}/pick-lists/${id}/verify`,
  },
  deliveries: {
    root: `${api}/deliveries`,
    byID: (id: number) => `${api}/deliveries/${id}`,
    dispatch: (id: number) => `${api}/deliveries/${id}/dispatch`,
    complete: (id: number) => `${api}/deliveries/${id}/complete`,
  },
  returns: {
    root: `${api}/returns`,
    byID: (id: number) => `${api}/returns/${id}`,
    approve: (id: number) => `${api}/returns/${id}/approve`,
    resolve: (id: number) => `${api}/returns/${id}/resolve`,
  },
  payments: {
    root: `${api}/payments`,
    byID: (id: number) => `${api}/payments/${id}`,
    confirm: (id: number) => `${api}/payments/${id}/confirm`,
    reverseAllocation: `${api}/payments/allocations/reverse`,
  },
} as const;
