using MarketSphere.Domain.Enums;

namespace MarketSphere.Application.Modules.CRM.DTOs;

public sealed record ClientListDto(int ClientID, string ClientCode, string ClientName, ClientType ClientType, SalesChannel Channel, string? Phone, ClientLifecycleStatus LifecycleStatus, ClientRiskStatus RiskStatus, bool IsActive);
public sealed record ClientContactDto(int ClientContactID, string ContactName, string? Designation, string? Phone, string? Email, bool IsPrimary, bool IsActive);
public sealed record ClientCreditProfileDto(int ClientCreditProfileID, decimal CreditLimit, int CreditDays, decimal CurrentDue, bool IsBlocked, string? BlockReason, DateTime? LastReviewedAt);
public sealed record ClientSegmentAssignmentDto(int ClientSegmentAssignmentID, int ClientSegmentID, string SegmentCode, string SegmentName, DateTime AssignedAt, DateTime? EffectiveTo);
public sealed record ClientDetailsDto(int ClientID, string ClientCode, string ClientName, ClientType ClientType, SalesChannel Channel, string? Phone, string? Email, string Address, decimal? GPSLat, decimal? GPSLng, int? RegionID, int? AreaID, int? TerritoryID, ClientLifecycleStatus LifecycleStatus, ClientRiskStatus RiskStatus, DateTime? LastOrderAt, bool IsActive, IReadOnlyCollection<ClientContactDto> Contacts, ClientCreditProfileDto? CreditProfile, IReadOnlyCollection<ClientSegmentAssignmentDto> Segments);
public class SaveClientRequestDto { public string ClientCode { get; init; } = string.Empty; public string ClientName { get; init; } = string.Empty; public ClientType ClientType { get; init; } public SalesChannel Channel { get; init; } public string? Phone { get; init; } public string? Email { get; init; } public string Address { get; init; } = string.Empty; public decimal? GPSLat { get; init; } public decimal? GPSLng { get; init; } public int? RegionID { get; init; } public int? AreaID { get; init; } public int? TerritoryID { get; init; } public ClientLifecycleStatus LifecycleStatus { get; init; } = ClientLifecycleStatus.Active; public ClientRiskStatus RiskStatus { get; init; } = ClientRiskStatus.Normal; public bool IsActive { get; init; } = true; }
public sealed class SaveClientContactRequestDto { public string ContactName { get; init; } = string.Empty; public string? Designation { get; init; } public string? Phone { get; init; } public string? Email { get; init; } public bool IsPrimary { get; init; } public bool IsActive { get; init; } = true; }
public sealed class SaveClientCreditProfileRequestDto { public decimal CreditLimit { get; init; } public int CreditDays { get; init; } public decimal CurrentDue { get; init; } public bool IsBlocked { get; init; } public string? BlockReason { get; init; } }
public sealed class ChangeClientLifecycleRequestDto { public ClientLifecycleStatus LifecycleStatus { get; init; } public string? Reason { get; init; } }
public sealed class AssignClientSegmentRequestDto { public int ClientSegmentID { get; init; } public DateTime? EffectiveTo { get; init; } }
public sealed record ClientSegmentDto(int ClientSegmentID, string SegmentCode, string SegmentName, ClientSegmentType SegmentType, string? Description, bool IsSystemSegment, bool IsActive);
public sealed class SaveClientSegmentRequestDto { public string SegmentCode { get; init; } = string.Empty; public string SegmentName { get; init; } = string.Empty; public ClientSegmentType SegmentType { get; init; } public string? Description { get; init; } public bool IsSystemSegment { get; init; } public bool IsActive { get; init; } = true; }
