using MarketSphere.Domain.Enums;

namespace MarketSphere.Application.Modules.CRM.DTOs;

public sealed record LeadListDto(int LeadID, string LeadCode, string LeadName, string? BusinessName, string? Phone, LeadSource Source, int CurrentScore, LeadTemperature Temperature, LeadStatus Status, DateTime? NextFollowUpAt, int? AssignedEmployeeID);
public sealed record LeadDetailsDto(int LeadID, string LeadCode, string LeadName, string? BusinessName, string? Phone, string? Email, LeadSource Source, int? SourceCampaignID, int? AssignedEmployeeID, int? RegionID, string? ProductInterest, decimal? EstimatedValue, int CurrentScore, LeadTemperature Temperature, LeadStatus Status, DateTime? NextFollowUpAt, string? LostReason, DateTime? ReactivationAt, int? ConvertedClientID);
public class SaveLeadRequestDto { public string LeadCode { get; init; } = string.Empty; public string LeadName { get; init; } = string.Empty; public string? BusinessName { get; init; } public string? Phone { get; init; } public string? Email { get; init; } public LeadSource Source { get; init; } public int? SourceCampaignID { get; init; } public int? AssignedEmployeeID { get; init; } public int? RegionID { get; init; } public string? ProductInterest { get; init; } public decimal? EstimatedValue { get; init; } public DateTime? NextFollowUpAt { get; init; } }
public sealed class ChangeLeadStatusRequestDto { public LeadStatus Status { get; init; } public string? LostReason { get; init; } }
public sealed record LeadScoreResultDto(int LeadID, int PreviousScore, int CurrentScore, LeadTemperature Temperature, IReadOnlyCollection<string> AppliedRules);
public sealed record DuplicateCandidateDto(string EntityType, int EntityID, string DisplayName, decimal MatchScore, IReadOnlyCollection<string> Reasons);
public sealed record DuplicateReviewDto(int DuplicateReviewCaseID, string SourceEntityType, int SourceEntityID, string MatchedEntityType, int MatchedEntityID, decimal? MatchScore, string? MatchReasonsJson, DuplicateReviewStatus Status, DuplicateResolutionType? ResolutionType, int? SurvivorEntityID, DateTime? ResolvedAt);
public sealed class ResolveDuplicateReviewRequestDto { public DuplicateResolutionType ResolutionType { get; init; } public int? SurvivorEntityID { get; init; } }
public sealed record LeadScoreRuleDto(int LeadScoreRuleID, string RuleName, LeadScoreConditionType ConditionType, ComparisonOperator Operator, string? ComparisonValue, int ScoreValue, DateOnly EffectiveFrom, DateOnly? EffectiveTo, bool IsActive);
public sealed class SaveLeadScoreRuleRequestDto { public string RuleName { get; init; } = string.Empty; public LeadScoreConditionType ConditionType { get; init; } public ComparisonOperator Operator { get; init; } public string? ComparisonValue { get; init; } public int ScoreValue { get; init; } public DateOnly EffectiveFrom { get; init; } public DateOnly? EffectiveTo { get; init; } public bool IsActive { get; init; } = true; }
public sealed class ConvertLeadToClientRequestDto { public string ClientCode { get; init; } = string.Empty; public ClientType ClientType { get; init; } public SalesChannel Channel { get; init; } public string Address { get; init; } = string.Empty; }
